FROM ubuntu:22.04
# APT清华源
RUN sed -i 's/archive.ubuntu.com/mirrors.tuna.tsinghua.edu.cn/g' /etc/apt/sources.list \
    && sed -i 's/security.ubuntu.com/mirrors.tuna.tsinghua.edu.cn/g' /etc/apt/sources.list

RUN apt-get update && apt-get install -y --no-install-recommends \
    libreoffice-core \
    libreoffice-impress \
    libreoffice-writer \
    libreoffice-calc \
    libreoffice-draw \
    pandoc \
    curl \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 8100 8200
CMD ["tail", "-f", "/dev/null"]