"""initial schema

Revision ID: 78df46d5c70c
Revises: 
Create Date: 2026-08-11 17:58:13.981253
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '001_initial'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_table('system_config',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_system_config'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), server_default=sa.text("'user'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key_prefix', sa.String(length=8), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_api_keys_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys'))
    )
    op.create_index('ix_api_keys_user_id', 'api_keys', ['user_id'], unique=False)
    op.create_table('collections',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_collections_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collections'))
    )
    op.create_index('ix_collections_user_id', 'collections', ['user_id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('original_name', sa.String(length=500), nullable=False),
    sa.Column('uploaded_type', sa.String(length=20), nullable=False),
    sa.Column('source_content', sa.Text(), nullable=True),
    sa.Column('type_hint', sa.String(length=20), nullable=True),
    sa.Column('stored_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('identified_type', sa.String(length=50), nullable=True),
    sa.Column('content_type', sa.String(length=30), nullable=True),
    sa.Column('identified_confidence', sa.Float(), nullable=True),
    sa.Column('mime_type', sa.String(length=200), nullable=True),
    sa.Column('is_suspicious', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'uploaded'"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_files_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_files'))
    )
    op.create_index('ix_files_content_type', 'files', ['content_type'], unique=False)
    op.create_index('ix_files_created_at_desc', 'files', [sa.text('created_at DESC')], unique=False)
    op.create_index('ix_files_original_name_trgm', 'files', ['original_name'], unique=False, postgresql_using='gin', postgresql_ops={'original_name': 'gin_trgm_ops'})
    op.create_index('ix_files_status', 'files', ['status'], unique=False)
    op.create_index('ix_files_user_id', 'files', ['user_id'], unique=False)
    op.create_table('file_identifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('layer', sa.SmallInteger(), nullable=False),
    sa.Column('detected_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_final', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_file_identifications_file_id_files'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_identifications'))
    )
    op.create_index('ix_file_identifications_file_id', 'file_identifications', ['file_id'], unique=False)
    op.create_table('parse_tasks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('parser_type', sa.String(length=50), nullable=True),
    sa.Column('output_formats', sa.String(length=50), server_default=sa.text("'markdown,json'"), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('progress', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retry_count', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_parse_tasks_file_id_files'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_parse_tasks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parse_tasks'))
    )
    op.create_index('ix_parse_tasks_created_at_desc', 'parse_tasks', [sa.text('created_at DESC')], unique=False)
    op.create_index('ix_parse_tasks_file_id', 'parse_tasks', ['file_id'], unique=False)
    op.create_index('ix_parse_tasks_status', 'parse_tasks', ['status'], unique=False)
    op.create_index('ix_parse_tasks_user_id', 'parse_tasks', ['user_id'], unique=False)
    op.create_table('collection_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('content_type', sa.String(length=30), nullable=False),
    sa.Column('identified_type', sa.String(length=50), nullable=True),
    sa.Column('original_name', sa.String(length=500), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_collection_items_collection_id_collections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_collection_items_file_id_files'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['parse_tasks.id'], name=op.f('fk_collection_items_task_id_parse_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_collection_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_items'))
    )
    op.create_index('ix_collection_items_collection_id', 'collection_items', ['collection_id'], unique=False)
    op.create_index('ix_collection_items_content_type', 'collection_items', ['content_type'], unique=False)
    op.create_index('ix_collection_items_tags', 'collection_items', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('ix_collection_items_user_id', 'collection_items', ['user_id'], unique=False)
    op.create_table('parse_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('output_format', sa.String(length=20), nullable=False),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('output_path', sa.String(length=1000), nullable=True),
    sa.Column('json_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_size', sa.BigInteger(), nullable=True),
    sa.Column('processing_time_ms', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_parse_results_file_id_files'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['parse_tasks.id'], name=op.f('fk_parse_results_task_id_parse_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parse_results'))
    )
    op.create_index('ix_parse_results_file_id', 'parse_results', ['file_id'], unique=False)
    op.create_index('ix_parse_results_task_id', 'parse_results', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_parse_results_task_id', table_name='parse_results')
    op.drop_index('ix_parse_results_file_id', table_name='parse_results')
    op.drop_table('parse_results')
    op.drop_index('ix_collection_items_user_id', table_name='collection_items')
    op.drop_index('ix_collection_items_tags', table_name='collection_items', postgresql_using='gin')
    op.drop_index('ix_collection_items_content_type', table_name='collection_items')
    op.drop_index('ix_collection_items_collection_id', table_name='collection_items')
    op.drop_table('collection_items')
    op.drop_index('ix_parse_tasks_user_id', table_name='parse_tasks')
    op.drop_index('ix_parse_tasks_status', table_name='parse_tasks')
    op.drop_index('ix_parse_tasks_file_id', table_name='parse_tasks')
    op.drop_index('ix_parse_tasks_created_at_desc', table_name='parse_tasks')
    op.drop_table('parse_tasks')
    op.drop_index('ix_file_identifications_file_id', table_name='file_identifications')
    op.drop_table('file_identifications')
    op.drop_index('ix_files_user_id', table_name='files')
    op.drop_index('ix_files_status', table_name='files')
    op.drop_index('ix_files_original_name_trgm', table_name='files', postgresql_using='gin', postgresql_ops={'original_name': 'gin_trgm_ops'})
    op.drop_index('ix_files_created_at_desc', table_name='files')
    op.drop_index('ix_files_content_type', table_name='files')
    op.drop_table('files')
    op.drop_index('ix_collections_user_id', table_name='collections')
    op.drop_table('collections')
    op.drop_index('ix_api_keys_user_id', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('users')
    op.drop_table('system_config')
    # ### end Alembic commands ###
